apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playeconomy-tls-cert
spec:
  secretName: playeconomy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "playeconomy.eastus.cloudapp.azure.com"